#!/usr/bin/env python

import sys
import PyPDF2

args = sys.argv
merger = PyPDF2.PdfFileMerger()

try:
    for path in args[1:-1]:
        merger.append(path)

    merger.write(args[-1])
finally:
    merger.close()
